export default {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  GET_USER: 'GET_USER',
  PLAY_COMPUTER: 'PLAY_COMPUTER',
  PLAY_ONLINE: 'PLAY_ONLINE',
  EXIT: 'EXIT',
  FINDING: 'FINDING'
};
